name: Common setup

inputs:
  client-repo:
    required: true
    type: string
  build-type:
    required: true
    type: string
  target-device:
    required: true
    type: string
  host-platform:
    required: true
    type: string
  build-mode:
    required: true
    type: string
  upload-enabled:
    required: true
    type: boolean
  python-version:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Set REPO_DIR and Dump environment
      shell: bash --noprofile --norc -xeuo pipefail {0}
      run: |
        echo "REPO_DIR=$(pwd)" >> $GITHUB_ENV
        env

    - name: Set environment variables
      shell: bash --noprofile --norc -xeuo pipefail {0}
      run: |

        WITH_TESTS_STR=''
        if [[ ("${{ inputs.upload-enabled }}" == "false") && ("${{ inputs.build-type }}" != "ci") ]]; then
          WITH_TESTS_STR='-with_tests'
        fi

        TARGET_PLATFORM='linux-64'
        if [[ "${{ inputs.host-platform }}" == "linux-aarch64" ]]; then
          TARGET_PLATFORM='linux-aarch64'
        fi

        BUILD_MODE="${{ inputs.build-mode }}"
        BUILD_MODE_STR=""
        [ -n "${BUILD_MODE}" ] && BUILD_MODE_STR="-${BUILD_MODE}"

        if [[ ("${BUILD_MODE}" == "") || ("${BUILD_MODE}" == "release") ]]; then
          # We upload release versions in the default folder.
          PKG_DIR="${TARGET_PLATFORM}"
        else
          PKG_DIR="${BUILD_MODE}/${TARGET_PLATFORM}"
        fi

        PYTHON_VERSION_FORMATTED=$(echo '${{ inputs.python-version }}' | tr -d '.')

        echo "BINDINGS_ARTIFACT_NAME=${{ inputs.host-platform }}-${{ inputs.build-type }}-cuda_bindings-python${PYTHON_VERSION_FORMATTED}-${{ inputs.target-device }}${BUILD_MODE_STR}${WITH_TESTS_STR}-${{ github.sha }}" >> $GITHUB_ENV
        echo "BINDINGS_ARTIFACTS_DIR=$(realpath "$(pwd)/cuda_bindings/dist")" >> $GITHUB_ENV
        echo "CORE_ARTIFACT_NAME=${{ inputs.host-platform }}-${{ inputs.build-type }}-cuda_core-python${PYTHON_VERSION_FORMATTED}-${{ inputs.target-device }}${BUILD_MODE_STR}${WITH_TESTS_STR}-${{ github.sha }}" >> $GITHUB_ENV
        echo "CORE_ARTIFACTS_DIR=$(realpath "$(pwd)/cuda_core/dist")" >> $GITHUB_ENV
        echo "USE_CUDA=${{ (inputs.target-device == 'cpu' && 'OFF') || 'ON' }}" >> $GITHUB_ENV
        echo "UPLOAD_ENABLED=${{ (inputs.upload-enabled  == 'true' && 'ON') || 'OFF' }}" >> $GITHUB_ENV
        echo "LEGATE_CORE_BUILD_MODE=${BUILD_MODE}" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
        echo "TARGET_PLATFORM=${TARGET_PLATFORM}" >> $GITHUB_ENV
        echo "PKG_DIR=${PKG_DIR}" >> $GITHUB_ENV
        echo "PYTHON_VERSION=${{ inputs.python-version }}" >> $GITHUB_ENV
