# This file was generated by stubgen-pyx v0.2.22 from cuda_core/cuda/core/_build_info.pyx

"""What this build of cuda.core compiled against.

``CUDA_MAJOR`` and ``CUDA_BINDINGS_FLOOR`` come from the compile-time environment
that build_hooks.py sets. ``CUDA_VERSION`` is the ``CUDA_VERSION`` macro of the
``cuda.h`` that the compiler resolved when it built this module, so the record
cannot disagree with the binaries. ``cuda/core/__init__.py`` reads this module
before it selects the build. The module imports nothing.
"""
CUDA_MAJOR: int = ...
CUDA_VERSION: int = ...
CUDA_BINDINGS_FLOOR: tuple[int, int, int] = ...
