# This file was generated by stubgen-pyx v0.2.6 from cuda_core/cuda/core/_dlpack.pyx

from __future__ import annotations

from enum import IntEnum

_DLDeviceType = int
DLDataTypeCode = int

class DLDeviceType(IntEnum):
    kDLCPU = 1
    kDLCUDA = 2
    kDLCUDAHost = 3
    kDLCUDAManaged = 13

def make_py_capsule(buf: object, versioned: bool) -> object:
    ...

def classify_dl_device(buf) -> tuple[int, int]:
    """Classify a buffer into a DLPack (device_type, device_id) pair.

    ``buf`` must expose ``is_device_accessible``, ``is_host_accessible``,
    ``is_managed``, and ``device_id`` attributes.
    """