# This file was generated by stubgen-pyx v0.2.22 from cuda_core/cuda/core/_kernel_arg_handler.pyx

from typing import Any, Sequence, TypedDict

from _typeshed import Incomplete
from typing_extensions import TypeAlias

cpp_single_complex: TypeAlias = Incomplete
cpp_double_complex: TypeAlias = Incomplete
voidptr: TypeAlias = Any

class __half_raw(TypedDict):
    x: int

class ParamHolder:
    ptr: int

    def __init__(self, kernel_args: Sequence[Any]) -> None: ...
    def __dealloc__(self) -> None: ...
