# This file was generated by stubgen-pyx v0.2.19 from cuda_core/cuda/core/_kernel_arg_handler.pyx

from typing import Any, Sequence, TypeAlias, TypedDict

cpp_single_complex: TypeAlias = Any
cpp_double_complex: TypeAlias = Any

class __half_raw(TypedDict):
    x: int

class ParamHolder:
    ptr: int

    def __init__(self, kernel_args: Sequence[Any]) -> None: ...
    def __dealloc__(self) -> None: ...
