# This file was generated by stubgen-pyx v0.2.6 from cuda_core/cuda/core/_kernel_arg_handler.pyx

from __future__ import annotations

from typing import Sequence

from libcpp.complex import complex as cpp_complex


class ParamHolder:

    def __init__(self, kernel_args: Sequence) -> None:
        ...

    def __dealloc__(self):
        ...
cpp_single_complex = cpp_complex.complex
cpp_double_complex = cpp_complex.complex