# This file was generated by stubgen-pyx v0.2.6 from cuda_core/cuda/core/_mipmapped_array.pyx

from __future__ import annotations


class MipmappedArray:
    """A mipmapped CUDA array for texture/surface access across levels.

    Wraps ``CUmipmappedArray``. Each mip level is a distinct, hardware-laid-out
    allocation accessible only via a :class:`TextureObject` (or by retrieving
    the level's :class:`CUDAArray` and binding it as a :class:`SurfaceObject`).
    Destroying the :class:`MipmappedArray` destroys all level arrays
    implicitly, so the :class:`CUDAArray` instances returned by :meth:`get_level`
    are non-owning and hold a strong reference back to their parent.

    Construct via :meth:`from_descriptor`.
    """

    def close(self):
        """Destroy the underlying ``CUmipmappedArray`` if owned.

        After ``close()`` any level :class:`CUDAArray` returned by :meth:`get_level`
        becomes invalid; callers must not access them.
        """

    def __init__(self, *args, **kwargs):
        ...

    @classmethod
    def from_descriptor(cls, *, shape, format, num_channels, num_levels, is_surface_load_store=False):
        """Allocate a new mipmapped CUDA array.

        Parameters
        ----------
        shape : tuple of int
            ``(width,)``, ``(width, height)``, or ``(width, height, depth)``
            in elements, for the base (level 0) mip.
        format : ArrayFormat
            Element format.
        num_channels : int
            Channels per element. Must be 1, 2, or 4.
        num_levels : int
            Number of mip levels to allocate; must be >= 1. The driver caps
            this at the log2 of the largest dimension; passing a larger value
            yields a driver error.
        is_surface_load_store : bool
            If True, allocate with ``CUDA_ARRAY3D_SURFACE_LDST`` so individual
            levels (obtained via :meth:`get_level`) can be bound as
            :class:`SurfaceObject` for kernel-side writes. Default False.

        Returns
        -------
        MipmappedArray
        """

    def get_level(self, level):
        """Return a non-owning :class:`CUDAArray` view of the given mip level.

        Parameters
        ----------
        level : int
            Mip level index in ``[0, num_levels)``.

        Returns
        -------
        CUDAArray
            A non-owning :class:`CUDAArray` wrapping the level's ``CUarray``.
            The :class:`MipmappedArray` is kept alive for the lifetime of the
            returned :class:`CUDAArray`; the underlying storage is released only
            when this :class:`MipmappedArray` is destroyed.
        """

    @property
    def handle(self):
        """The underlying ``CUmipmappedArray`` as an integer."""

    @property
    def shape(self):
        """Base-level (level 0) allocation shape, in elements."""

    @property
    def format(self):
        """The element :class:`ArrayFormat`."""

    @property
    def num_channels(self):
        """Channels per element (1, 2, or 4)."""

    @property
    def num_levels(self):
        """Number of mip levels."""

    @property
    def is_surface_load_store(self):
        """True if this mipmap (and each of its levels) was created with
        ``CUDA_ARRAY3D_SURFACE_LDST`` and can back a :class:`SurfaceObject`."""

    @property
    def device(self):
        """The :class:`Device` this mipmap was allocated on."""

    def __dealloc__(self):
        ...

    def __enter__(self):
        ...

    def __exit__(self, exc_type, exc, tb):
        ...

    def __repr__(self):
        ...