# This file was generated by stubgen-pyx v0.2.22 from cuda_core/cuda/core/_resource_handles.pyx

from typing import Callable

from _typeshed import Incomplete
from cuda.bindings import cydriver
from typing_extensions import TypeAlias

ContextHandle: TypeAlias = Incomplete
GreenCtxHandle: TypeAlias = Incomplete
StreamHandle: TypeAlias = Incomplete
EventHandle: TypeAlias = Incomplete
MemoryPoolHandle: TypeAlias = Incomplete
DevicePtrHandle: TypeAlias = Incomplete
LibraryHandle: TypeAlias = Incomplete
KernelHandle: TypeAlias = Incomplete
GraphHandle: TypeAlias = Incomplete
GraphExecHandle: TypeAlias = Incomplete
GraphNodeHandle: TypeAlias = Incomplete
GraphicsResourceHandle: TypeAlias = Incomplete
NvrtcProgramHandle: TypeAlias = Incomplete
NvvmProgramHandle: TypeAlias = Incomplete
NvJitLinkHandle: TypeAlias = Incomplete
CuLinkHandle: TypeAlias = Incomplete
FileDescriptorHandle: TypeAlias = Incomplete
OpaqueArrayHandle: TypeAlias = Incomplete
MipmappedArrayHandle: TypeAlias = Incomplete
TexObjectHandle: TypeAlias = Incomplete
SurfObjectHandle: TypeAlias = Incomplete
OpaqueHandle: TypeAlias = Incomplete
PreparedAttachment: TypeAlias = Incomplete
PreparedChildGraphUpdate: TypeAlias = Incomplete
PreparedExecAttachment: TypeAlias = Incomplete
MRDeallocCallback: TypeAlias = Callable[[object, cydriver.CUdeviceptr, int, StreamHandle], None]
NvvmProgramValue: TypeAlias = Incomplete
NvJitLinkValue: TypeAlias = Incomplete
TexObjectValue: TypeAlias = Incomplete
SurfObjectValue: TypeAlias = Incomplete
PreparedAttachmentState: TypeAlias = Incomplete
PreparedAttachmentDeleter: TypeAlias = Incomplete
PreparedChildGraphUpdateState: TypeAlias = Incomplete
PreparedExecAttachmentState: TypeAlias = Incomplete
PreparedExecAttachmentDeleter: TypeAlias = Incomplete

def _set_context_restore_fault_for_testing(status: int):
    """Make the next context restoration on this thread fail with ``status``.

    Test hook for the context save/restore paths in the handle layer. The
    injected failure leaves the target context current, exactly as a failing
    ``cuCtxSetCurrent`` would, so callers must restore the context themselves.
    """
def _note_or_report_cuda_error_for_testing(status: int):
    """Attach a failed CUDA call to the exception being handled, or report it.

    Test hook for ``note_or_report_cuda_error()``. Called inside an ``except``
    block it adds a note to the exception being handled (Python 3.11+); anywhere
    else it emits a ``CUDAWarning``.
    """
