# This file was generated by stubgen-pyx v0.2.6 from cuda_core/cuda/core/_resource_handles.pyx

from __future__ import annotations

from libcpp.memory import shared_ptr

ContextHandle = shared_ptr
GreenCtxHandle = shared_ptr
StreamHandle = shared_ptr
EventHandle = shared_ptr
MemoryPoolHandle = shared_ptr
DevicePtrHandle = shared_ptr
LibraryHandle = shared_ptr
KernelHandle = shared_ptr
GraphHandle = shared_ptr
GraphExecHandle = shared_ptr
GraphNodeHandle = shared_ptr
GraphicsResourceHandle = shared_ptr
NvrtcProgramHandle = shared_ptr
NvvmProgramHandle = shared_ptr
NvJitLinkHandle = shared_ptr
CuLinkHandle = shared_ptr
FileDescriptorHandle = shared_ptr