# This file was generated by stubgen-pyx v0.2.19 from cuda_core/cuda/core/_resource_handles.pyx

from typing import Any, TypeAlias

ContextHandle: TypeAlias = Any
GreenCtxHandle: TypeAlias = Any
StreamHandle: TypeAlias = Any
EventHandle: TypeAlias = Any
MemoryPoolHandle: TypeAlias = Any
DevicePtrHandle: TypeAlias = Any
LibraryHandle: TypeAlias = Any
KernelHandle: TypeAlias = Any
GraphHandle: TypeAlias = Any
GraphExecHandle: TypeAlias = Any
GraphNodeHandle: TypeAlias = Any
GraphicsResourceHandle: TypeAlias = Any
NvrtcProgramHandle: TypeAlias = Any
NvvmProgramHandle: TypeAlias = Any
NvJitLinkHandle: TypeAlias = Any
CuLinkHandle: TypeAlias = Any
FileDescriptorHandle: TypeAlias = Any
OpaqueArrayHandle: TypeAlias = Any
MipmappedArrayHandle: TypeAlias = Any
TexObjectHandle: TypeAlias = Any
SurfObjectHandle: TypeAlias = Any
OpaqueHandle: TypeAlias = Any
PreparedAttachment: TypeAlias = Any
PreparedChildGraphUpdate: TypeAlias = Any
PreparedExecAttachment: TypeAlias = Any
