# This file was generated by stubgen-pyx v0.2.6 from cuda_core/cuda/core/_memory/_copy_ops.pyx

from __future__ import annotations

from collections.abc import Sequence

from cuda.core._memory._buffer import Buffer


def copy_batch(stream: object, srcs: Sequence[Buffer], dsts: Sequence[Buffer], *, options: object=None) -> None:
    """Copy a batch of buffers asynchronously.

    Requires CUDA 13+. For a single buffer, use
    :meth:`Buffer.copy_to` or :meth:`Buffer.copy_from`.

    The driver provides no graph-node form of ``cuMemcpyBatchAsync``, so
    this cannot be captured into a graph. Build graph copies with
    :meth:`graph.GraphNode.memcpy` or per-buffer :meth:`Buffer.copy_to`.

    Parameters
    ----------
    stream : :class:`~_stream.Stream`
        Stream for the asynchronous copy. Passing a
        :class:`~graph.GraphBuilder` raises ``CUDAError``
        (``CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED``).
    srcs : Sequence[:class:`Buffer`]
        Source buffers.  Must be a sequence, not a single Buffer.
    dsts : Sequence[:class:`Buffer`]
        Destination buffers.  Must match ``len(srcs)``.
    options : :class:`CopyOptions` | Sequence[:class:`CopyOptions`] | None
        Per-copy options. A single value applies to every copy; a
        sequence pairs by index and must match ``len(srcs)``. ``None``
        uses stream-ordered defaults.

    Raises
    ------
    NotImplementedError
        On a CUDA 12 build of ``cuda.core``.
    ValueError
        If lengths or sizes mismatch.
    TypeError
        If a single Buffer is passed instead of a sequence.
    UserWarning
        If ``overlap_mode='prefer_overlap_with_compute'`` is requested
        on a non-integrated (discrete) GPU.
    """