# This file was generated by stubgen-pyx v0.2.22 from cuda_core/cuda/core/_memory/_ipc.pyx

import uuid
from typing import Any, Iterable

from cuda.core.typing import VirtualMemoryHandleType

__all__ = []

class IPCDataForBuffer:
    """Data members related to sharing memory buffers via IPC."""
    def __init__(self, ipc_descriptor: IPCBufferDescriptor, is_mapped: bool) -> None: ...
    @property
    def ipc_descriptor(self) -> IPCBufferDescriptor: ...
    @property
    def is_mapped(self) -> bool: ...

class IPCDataForMR:
    """Data members related to sharing memory resources via IPC."""
    def __init__(self, alloc_handle: IPCAllocationHandle, is_mapped: bool) -> None: ...
    @property
    def alloc_handle(self) -> IPCAllocationHandle: ...
    @property
    def is_mapped(self) -> bool: ...
    @property
    def uuid(self) -> uuid.UUID | None: ...

class IPCBufferDescriptor:
    """Serializable object describing a buffer that can be shared between processes.

    Note
    ----
    The payload and ``size`` fields are controlled by the exporting peer.
    Receivers must treat them as untrusted and import only through
    :meth:`Buffer.from_ipc_descriptor`.
    """
    def __init__(self, *arg, **kwargs) -> None: ...
    @staticmethod
    def _init(reserved: bytes, size: int) -> IPCBufferDescriptor: ...
    def __reduce__(self) -> tuple[object, ...]: ...
    @property
    def size(self) -> int: ...

class IPCAllocationHandle:
    """Shareable OS handle to an IPC-enabled memory pool or to a physical allocation
    of a :class:`VirtualMemoryResource` buffer."""
    def __init__(self, *arg, **kwargs) -> None: ...
    @classmethod
    def _init(cls, handle: int, uuid: uuid.UUID | None) -> IPCAllocationHandle: ...
    def close(self):
        """Close the handle."""
    @property
    def is_closed(self) -> bool:
        """Whether this allocation handle has been closed."""
    def __int__(self) -> int: ...
    @property
    def handle(self) -> int: ...
    @property
    def uuid(self) -> uuid.UUID: ...

class VirtualMemoryIPCBufferDescriptor(IPCBufferDescriptor):
    """Serializable object describing a :class:`VirtualMemoryBuffer` that can be shared between processes.

    The descriptor holds one exported handle per physical allocation that
    backs the buffer, in address order (``handles``), with each allocation's
    size (``sizes``) and the buffer's size (``size``, which may be smaller
    than their sum). With POSIX file descriptors the handles are
    :class:`IPCAllocationHandle` objects: the descriptor owns them and closes
    them when it is released.

    A descriptor pins the physical memory while it exists, in every process
    that holds one, and nothing else does: the exporting buffer keeps no
    descriptor, and an imported buffer does not keep the one it came from. A
    descriptor parked in a ``multiprocessing`` ``Queue`` or sent to a ``Pool``
    pins the memory in the sender until the receiver has unpickled it; a
    buffer passed as a ``Process`` argument pins it until the ``Process``
    object is released, because the child receives the file descriptors when
    it is spawned.

    Two transports exist. ``multiprocessing`` (a ``Queue``, a ``Pipe``,
    ``Process`` arguments, or a ``Pool``) pickles the descriptor, or a buffer,
    and duplicates the file descriptors into the receiving process; plain
    ``pickle`` cannot carry them and raises. A process with its own file
    descriptor passing sends ``fds``, ``sizes``, ``handle_type``, and ``size``
    itself, and the receiver rebuilds the descriptor with :meth:`from_fds`.

    Note
    ----
    The sizes are controlled by the exporting peer. Receivers must treat them
    as untrusted and import only through :meth:`Buffer.from_ipc_descriptor`,
    which checks what it can and fails instead of mapping a size the driver
    rejects.
    """
    _handle_type: int
    _chunk_sizes: tuple[Any, ...]
    _handles: tuple[Any, ...]

    @staticmethod
    def _from_exports(handle_type: int, chunk_sizes: tuple[int, ...], handles: tuple[Any, ...], size: int) -> VirtualMemoryIPCBufferDescriptor: ...
    @classmethod
    def from_fds(cls, fds: Iterable[int | IPCAllocationHandle], sizes: Iterable[int], *, handle_type: VirtualMemoryHandleType | str='posix_fd', size: int | None=None) -> VirtualMemoryIPCBufferDescriptor:
        """Build a descriptor from file descriptors received outside ``multiprocessing``.

        The exporter sends ``fds``, ``sizes``, ``handle_type``, and ``size``
        of its descriptor through a transport of its own (a Unix socket with
        ``SCM_RIGHTS``, for example); the receiver rebuilds the descriptor
        here and imports it with :meth:`Buffer.from_ipc_descriptor`.

        Parameters
        ----------
        fds : Iterable[int | IPCAllocationHandle]
            One handle per physical allocation, in address order, as the
            exporter's ``fds`` listed them. An ``int`` is duplicated: the
            caller keeps ownership of the original and closes it. An
            :class:`IPCAllocationHandle` is shared and closes with its last
            holder.
        sizes : Iterable[int]
            The exporter's ``sizes``, one per handle.
        handle_type : VirtualMemoryHandleType | str, optional
            The exporter's ``handle_type``; ``"posix_fd"`` by default.
        size : int, optional
            The exporter's ``size``, at most the sum of ``sizes``; the sum by
            default.

        Raises
        ------
        ValueError
            If the counts differ, a size is not positive, ``size`` exceeds the
            sum of ``sizes``, or ``handle_type`` cannot be shared.
        RuntimeError
            If an :class:`IPCAllocationHandle` is closed.
        OSError
            If an ``int`` is not an open file descriptor.
        """
    @property
    def handle_type(self) -> VirtualMemoryHandleType:
        """The handle type the exporter used; the importing resource must be configured with the same."""
    @property
    def sizes(self) -> tuple[int, ...]:
        """Size of each physical allocation, in address order; the sum is at least ``size``."""
    @property
    def handles(self) -> tuple[IPCAllocationHandle, ...]:
        """The exported handles, one per allocation, in address order; the descriptor owns them."""
    @property
    def fds(self) -> tuple[int, ...]:
        """The exported file descriptors as integers, for a transport of your own.

        They belong to this descriptor: send or duplicate them while it is
        alive. Each one is released when the descriptor is.
        """
    def __reduce__(self) -> tuple[object, ...]: ...

def _reduce_allocation_handle(alloc_handle: IPCAllocationHandle) -> tuple[object, ...]: ...
def _reconstruct_allocation_handle(cls: type, df: object, uuid: uuid.UUID | None) -> IPCAllocationHandle: ...
