# This file was generated by stubgen-pyx v0.2.6 from cuda_core/cuda/core/_memory/_ipc.pyx

from __future__ import annotations

import uuid


class IPCDataForBuffer:
    """Data members related to sharing memory buffers via IPC."""

    def __cinit__(self, ipc_descriptor: IPCBufferDescriptor, is_mapped: bool):
        ...

    @property
    def ipc_descriptor(self):
        ...

    @property
    def is_mapped(self):
        ...

class IPCDataForMR:
    """Data members related to sharing memory resources via IPC."""

    def __cinit__(self, alloc_handle: IPCAllocationHandle, is_mapped: bool):
        ...

    @property
    def alloc_handle(self):
        ...

    @property
    def is_mapped(self):
        ...

    @property
    def uuid(self):
        ...

class IPCBufferDescriptor:
    """Serializable object describing a buffer that can be shared between processes."""

    def __init__(self, *arg, **kwargs):
        ...

    @staticmethod
    def _init(reserved: bytes, size: int):
        ...

    def __reduce__(self):
        ...

    @property
    def size(self):
        ...

class IPCAllocationHandle:
    """Shareable handle to an IPC-enabled device memory pool."""

    def close(self):
        """Close the handle."""

    def __init__(self, *arg, **kwargs):
        ...

    @classmethod
    def _init(cls, handle: int, uuid):
        ...

    def __int__(self) -> int:
        ...

    @property
    def handle(self) -> int:
        ...

    @property
    def uuid(self) -> uuid.UUID:
        ...
__all__ = ['IPCBufferDescriptor', 'IPCAllocationHandle']

def _reduce_allocation_handle(alloc_handle):
    ...

def _reconstruct_allocation_handle(cls, df, uuid):
    ...