# This file was generated by stubgen-pyx v0.2.22 from cuda_core/cuda/core/_memory/_virtual_memory_resource.pyx

import platform
from dataclasses import dataclass, field
from typing import Iterable

from cuda.core._device import Device
from cuda.core._memory._buffer import Buffer, MemoryResource
from cuda.core._memory._ipc import (IPCBufferDescriptor,
                                    VirtualMemoryIPCBufferDescriptor)
from cuda.core._stream import Stream
from cuda.core._utils.cuda_utils import driver
from cuda.core.graph import GraphBuilder
from cuda.core.typing import (DevicePointerType, VirtualMemoryAccessType,
                              VirtualMemoryAllocationType,
                              VirtualMemoryGranularityType,
                              VirtualMemoryHandleType,
                              VirtualMemoryLocationType)

__all__ = ['VirtualMemoryBuffer', 'VirtualMemoryResource', 'VirtualMemoryResourceOptions']
_HOST_LOCATION_TYPES = frozenset({VirtualMemoryLocationType.HOST, VirtualMemoryLocationType.HOST_NUMA, VirtualMemoryLocationType.HOST_NUMA_CURRENT})
_IPC_HANDLE_TYPES = frozenset({VirtualMemoryHandleType.POSIX_FD}) if platform.system() == 'Linux' else frozenset()

@dataclass
class VirtualMemoryResourceOptions:
    """A configuration object for the VirtualMemoryResource
       Stores configuration information which tells the resource how to use the CUDA VMM APIs

    Attributes
    ----------
    allocation_type: :obj:`~_memory.VirtualMemoryAllocationType` | str
        Controls the type of allocation.
    location_type: :obj:`~_memory.VirtualMemoryLocationType` | str
        Controls the location of the allocation.
    handle_type: :obj:`~_memory.VirtualMemoryHandleType` | str
        Export handle type for the physical allocation. Use ``"posix_fd"`` on
        Linux if you plan to import/export the allocation. Use `None` if you
        don't need an exportable handle. ``location_type="host"`` requires
        `None`.
    gpu_direct_rdma: bool
        Hint that the allocation should be GDR-capable (if supported).
    granularity: :obj:`~_memory.VirtualMemoryGranularityType` | str
        Controls granularity query and size rounding.
    addr_hint: int
        A (optional) virtual address hint to try to reserve at. Setting it to 0 lets the CUDA driver decide.
    addr_align: int
        Alignment for the VA reservation. If `None`, use the queried granularity.
    peers: Iterable[int]
        Extra device IDs that should be granted access in addition to ``device``.
    self_access: :obj:`~_memory.VirtualMemoryAccessType` | None | str
        Access flags for the owning device.
    peer_access: :obj:`~_memory.VirtualMemoryAccessType` | None | str
        Access flags for peers.
    """
    allocation_type: VirtualMemoryAllocationType = VirtualMemoryAllocationType.PINNED
    location_type: VirtualMemoryLocationType = VirtualMemoryLocationType.DEVICE
    handle_type: VirtualMemoryHandleType = VirtualMemoryHandleType.POSIX_FD
    granularity: VirtualMemoryGranularityType = VirtualMemoryGranularityType.RECOMMENDED
    gpu_direct_rdma: bool = False
    addr_hint: int | None = 0
    addr_align: int | None = None
    peers: Iterable[int] = field(default_factory=tuple)
    self_access: VirtualMemoryAccessType = VirtualMemoryAccessType.READ_WRITE
    peer_access: VirtualMemoryAccessType = VirtualMemoryAccessType.READ_WRITE
    _a = driver.CUmemAccess_flags
    _access_flags = {VirtualMemoryAccessType.READ_WRITE: _a.CU_MEM_ACCESS_FLAGS_PROT_READWRITE, VirtualMemoryAccessType.READ: _a.CU_MEM_ACCESS_FLAGS_PROT_READ, None: 0}
    _h = driver.CUmemAllocationHandleType
    _handle_types = {None: _h.CU_MEM_HANDLE_TYPE_NONE, VirtualMemoryHandleType.POSIX_FD: _h.CU_MEM_HANDLE_TYPE_POSIX_FILE_DESCRIPTOR, VirtualMemoryHandleType.WIN32_KMT: _h.CU_MEM_HANDLE_TYPE_WIN32_KMT, VirtualMemoryHandleType.FABRIC: _h.CU_MEM_HANDLE_TYPE_FABRIC}
    _g = driver.CUmemAllocationGranularity_flags
    _granularity = {VirtualMemoryGranularityType.RECOMMENDED: _g.CU_MEM_ALLOC_GRANULARITY_RECOMMENDED, VirtualMemoryGranularityType.MINIMUM: _g.CU_MEM_ALLOC_GRANULARITY_MINIMUM}
    _l = driver.CUmemLocationType
    _location_type = {VirtualMemoryLocationType.DEVICE: _l.CU_MEM_LOCATION_TYPE_DEVICE, VirtualMemoryLocationType.HOST: _l.CU_MEM_LOCATION_TYPE_HOST, VirtualMemoryLocationType.HOST_NUMA: _l.CU_MEM_LOCATION_TYPE_HOST_NUMA, VirtualMemoryLocationType.HOST_NUMA_CURRENT: _l.CU_MEM_LOCATION_TYPE_HOST_NUMA_CURRENT}
    _t = driver.CUmemAllocationType
    _allocation_type = {VirtualMemoryAllocationType.PINNED: _t.CU_MEM_ALLOCATION_TYPE_PINNED}

    @staticmethod
    def _access_to_flags(spec: VirtualMemoryAccessType | None) -> int: ...
    @staticmethod
    def _allocation_type_to_driver(spec: VirtualMemoryAllocationType) -> int: ...
    @staticmethod
    def _location_type_to_driver(spec: VirtualMemoryLocationType) -> int: ...
    @staticmethod
    def _handle_type_to_driver(spec: VirtualMemoryHandleType | None) -> int: ...
    @staticmethod
    def _granularity_to_driver(spec: VirtualMemoryGranularityType) -> int: ...

class VirtualMemoryBuffer(Buffer):
    """A :class:`Buffer` returned by :class:`VirtualMemoryResource`.

    The buffer owns its address reservations, physical allocations and
    mappings through its device pointer handle; closing it is the only way
    to release them. A buffer returned by
    :meth:`VirtualMemoryResource.modify_allocation` aliases the buffer it
    was grown from: the two share their physical memory, and that memory is
    freed when the last buffer that maps it closes.
    """
    @property
    def ipc_descriptor(self) -> IPCBufferDescriptor:
        """Descriptor for sharing this buffer with other processes.

        The descriptor exports every physical allocation that backs the
        buffer as a shareable handle and is cached on the buffer until the
        buffer closes. Each exported allocation takes one file descriptor,
        and a live descriptor keeps the physical memory allocated in every
        process that holds a copy. It requires a resource whose
        ``handle_type`` can be shared; see
        :attr:`VirtualMemoryResource.is_ipc_enabled`. Import it with
        :meth:`Buffer.from_ipc_descriptor` and a
        :class:`VirtualMemoryResource` of the receiving process, or send the
        buffer itself through ``multiprocessing``. A buffer imported from
        another process cannot be exported again; share the descriptor it
        was imported from.
        """
    def close(self, stream: Stream | GraphBuilder | None=None) -> None:
        """Release this buffer's share of its address range.

        Each mapping, reservation and physical allocation goes away when the
        last buffer that holds it closes. Virtual memory is unmapped
        synchronously, so this call waits for the work queued on the
        deallocation stream before it releases this buffer's share; a buffer
        released by the garbage collector waits at that point instead. The
        unmap cannot be captured. When the stream this close uses, given or recorded, is not
        a default stream and is capturing, the call raises and leaves the
        buffer open. A default stream is checked when the range is released
        instead: if synchronizing it would disturb a capture in its context,
        the release reports a :class:`CUDAWarning` and unmaps without
        synchronizing that stream.

        Parameters
        ----------
        stream : :obj:`~_stream.Stream` | :obj:`~graph.GraphBuilder`, optional
            If given, replaces the recorded deallocation stream, as for
            :meth:`Buffer.close`.
        """

class VirtualMemoryResource(MemoryResource):
    """Create a device memory resource that uses the CUDA VMM APIs to allocate memory.

    Parameters
    ----------
    device_id : Device | int
        Device for which a memory resource is constructed.

    config : VirtualMemoryResourceOptions, optional
        A configuration object for the VirtualMemoryResource


    Warning
    -------
        This is a low-level API that is provided only for convenience. Make sure you fully understand
        how CUDA Virtual Memory Management works before using this. Other MemoryResource subclasses
        in cuda.core should already meet the common needs.

        A shared buffer's descriptor comes from the exporting process and is not trusted:
        :meth:`Buffer.from_ipc_descriptor` checks what it can, and the driver rejects a size that
        does not match the exported allocation. Unpickling a shared buffer performs a live import,
        so unpickle buffers only from a trusted principal.

    Notes
    -----
    Every buffer this resource returns is a :class:`VirtualMemoryBuffer` that
    owns its address reservations, physical allocations and mappings; closing
    the buffer releases them. :meth:`deallocate` is not involved in that path.

    Virtual memory is unmapped synchronously, so closing a buffer waits for
    the work queued on its deallocation stream. A buffer released by the
    garbage collector waits at that point instead. To control when the wait
    happens, close the buffer explicitly or record an idle stream with
    :meth:`Buffer.set_deallocation_stream`.

    Buffers can be shared with other processes when ``config.handle_type``
    is ``"posix_fd"`` (Linux). :attr:`Buffer.ipc_descriptor` exports the
    physical allocations that back a buffer, one file descriptor each;
    :meth:`Buffer.from_ipc_descriptor` imports them with a
    ``VirtualMemoryResource`` of the receiving process for the device that
    owns the memory; and a buffer sent through ``multiprocessing`` does both.
    Plain ``pickle`` cannot carry the file descriptors. The importing resource
    maps the memory for its device and the devices in its ``peers`` option,
    with its own access options. A live descriptor keeps the memory allocated
    in every process that holds a copy. An imported buffer, and a buffer grown
    from one, cannot be exported again. See :attr:`is_ipc_enabled`.
    """
    device: object
    config: object

    def __init__(self, device_id: Device | int, config: VirtualMemoryResourceOptions | None=None) -> None: ...
    def __reduce__(self) -> tuple[object, ...]: ...
    def allocate(self, size: int, *, stream: Stream | GraphBuilder | None=None) -> VirtualMemoryBuffer:
        """
        Allocate a buffer of the given size using CUDA virtual memory.

        Parameters
        ----------
        size : int
            The size in bytes of the buffer to allocate. It is rounded up to the
            allocation granularity; the returned buffer reports the rounded size.
        stream : :obj:`~_stream.Stream` | :obj:`~graph.GraphBuilder`, optional
            Keyword-only. The allocation itself is synchronous. A real stream is
            recorded as the buffer's deallocation stream and synchronized when
            the buffer closes; with `None` or a default-stream token the legacy
            default stream of the resource's device is recorded instead. A
            host-located resource records no default stream: its buffers close
            without a synchronization unless a real stream was given.

        Returns
        -------
        VirtualMemoryBuffer
            A buffer that owns its reservation, physical allocation and mapping.

        Raises
        ------
        CUDAError
            If any CUDA driver API call fails during allocation. Nothing is
            left allocated when this method raises.
        OverflowError
            If ``size`` rounded up to the granularity does not fit in ``size_t``.
        """
    def modify_allocation(self, buf: Buffer, new_size: int, config: VirtualMemoryResourceOptions | None=None) -> VirtualMemoryBuffer:
        """
        Grow a buffer of this resource to at least ``new_size`` bytes.

        The buffer passed in stays open and usable, and is never returned. The
        returned buffer aliases it: both map the same physical memory, which is
        freed when the last of the two closes. When the driver can extend the
        address range in place, the returned buffer has the same pointer;
        otherwise it has a new one and the existing contents are reachable
        through both. Closing the returned buffer never closes ``buf``. A
        buffer grown from an imported buffer maps imported memory and cannot
        be exported again.

        Concurrent calls on buffers that alias one another are safe.

        Parameters
        ----------
        buf : VirtualMemoryBuffer
            A buffer returned by :meth:`allocate` or by this method.
        new_size : int
            The requested total size in bytes; rounded up to the granularity.
        config : VirtualMemoryResourceOptions, optional
            Configuration for the new physical memory chunk only. Existing
            chunks keep the access they were created with, and the resource's
            own configuration is unchanged. It must name the resource's
            ``location_type`` and ``handle_type`` and passes the same checks
            as the constructor.
            When ``buf`` already covers ``new_size`` there is no new chunk, so
            ``config`` has no effect. This method never changes the access of
            memory that is already mapped.

        Returns
        -------
        VirtualMemoryBuffer
            A new buffer of at least ``new_size`` and at least ``buf.size``
            bytes. When ``buf`` already covers the request, the result is a
            full alias of it and no driver call is made.

        Raises
        ------
        TypeError
            If ``buf`` did not come from this resource.
        ValueError
            If ``config`` names a different location or handle type than the
            resource, or the constructor would reject it.
        RuntimeError
            If ``buf`` is closed, or ``config`` requests GPUDirect RDMA on a
            device without support.
        OverflowError
            If ``new_size`` rounded up to the granularity does not fit in
            ``size_t``.
        CUDAError
            If a driver call fails. ``buf`` is untouched when this method raises.
        """
    def deallocate(self, ptr: DevicePointerType, size: int, *, stream: Stream | GraphBuilder | None=None) -> None:
        """
        Unmap and free one address range that was reserved and mapped outside this resource.

        Buffers returned by :meth:`allocate` and :meth:`modify_allocation` free
        themselves when they close and never call this method. It exists for
        raw pointers wrapped with :meth:`Buffer.from_handle` with ``mr`` set to
        this resource: the range must be exactly one reservation, and the caller
        must already have released its own ``cuMemCreate`` handle, so the
        physical memory is freed by the unmap.

        Parameters
        ----------
        ptr : DevicePointerType
            The start of the reservation.
        size : int
            The size of the reservation in bytes.
        stream : :obj:`~_stream.Stream` | :obj:`~graph.GraphBuilder`, optional
            Keyword-only. If given, ``stream.sync()`` is called before the
            range is unmapped, except for a default-stream token on a
            host-located resource, which has no context to synchronize in.
        """
    @property
    def is_device_accessible(self) -> bool:
        """
        Indicates whether the allocated memory is accessible from the device.
        """
    @property
    def is_host_accessible(self) -> bool:
        """
        Indicates whether the allocated memory is accessible from the host.
        """
    @property
    def is_ipc_enabled(self) -> bool:
        """Whether buffers of this resource can be shared with other processes.

        True when ``config.handle_type`` is ``"posix_fd"`` on Linux. With
        ``handle_type=None`` the allocations cannot be exported, Win32 KMT
        handles are not transported by cuda.core, and fabric handles are not
        supported yet.
        """
    def _import_ipc_buffer(self, desc: VirtualMemoryIPCBufferDescriptor, stream) -> VirtualMemoryBuffer:
        """Import a buffer that another process exported; see :meth:`Buffer.from_ipc_descriptor`.

        Every exported allocation is imported with this resource's handle
        type and checked to live where this resource allocates (its device,
        or its host location). The allocations are then mapped in order into
        one new address reservation with the access descriptors this
        resource's options produce for its device and peers, and the
        deallocation stream is recorded as :meth:`allocate` does. The
        returned buffer owns the imported handles like a buffer from
        :meth:`allocate` owns created ones, reports ``is_mapped``, and cannot
        be exported again.
        """
    @property
    def device_id(self) -> int:
        """
        Get the device ID associated with this memory resource.

        Returns:
            int: CUDA device ID. -1 if the memory resource allocates host memory
        """
    def __repr__(self) -> str:
        """
        Return a string representation of the VirtualMemoryResource.

        Returns:
            str: A string describing the object
        """
