# This file was generated by stubgen-pyx v0.2.22 from cuda_core/cuda/core/_memory/_virtual_memory_resource.pyx

from dataclasses import dataclass, field
from typing import Iterable

from cuda.core._device import Device
from cuda.core._memory._buffer import Buffer, MemoryResource
from cuda.core._stream import Stream
from cuda.core._utils.cuda_utils import driver
from cuda.core.graph import GraphBuilder
from cuda.core.typing import (DevicePointerType, VirtualMemoryAccessType,
                              VirtualMemoryAllocationType,
                              VirtualMemoryGranularityType,
                              VirtualMemoryHandleType,
                              VirtualMemoryLocationType)

__all__ = ['VirtualMemoryBuffer', 'VirtualMemoryResource', 'VirtualMemoryResourceOptions']
_HOST_LOCATION_TYPES = frozenset({VirtualMemoryLocationType.HOST, VirtualMemoryLocationType.HOST_NUMA, VirtualMemoryLocationType.HOST_NUMA_CURRENT})

@dataclass
class VirtualMemoryResourceOptions:
    """A configuration object for the VirtualMemoryResource
       Stores configuration information which tells the resource how to use the CUDA VMM APIs

    Attributes
    ----------
    allocation_type: :obj:`~_memory.VirtualMemoryAllocationType` | str
        Controls the type of allocation.
    location_type: :obj:`~_memory.VirtualMemoryLocationType` | str
        Controls the location of the allocation.
    handle_type: :obj:`~_memory.VirtualMemoryHandleType` | str
        Export handle type for the physical allocation. Use ``"posix_fd"`` on
        Linux if you plan to import/export the allocation. Use `None` if you
        don't need an exportable handle. Host-located allocations require
        `None`.
    gpu_direct_rdma: bool
        Hint that the allocation should be GDR-capable (if supported).
    granularity: :obj:`~_memory.VirtualMemoryGranularityType` | str
        Controls granularity query and size rounding.
    addr_hint: int
        A (optional) virtual address hint to try to reserve at. Setting it to 0 lets the CUDA driver decide.
    addr_align: int
        Alignment for the VA reservation. If `None`, use the queried granularity.
    peers: Iterable[int]
        Extra device IDs that should be granted access in addition to ``device``.
    self_access: :obj:`~_memory.VirtualMemoryAccessType` | None | str
        Access flags for the owning device.
    peer_access: :obj:`~_memory.VirtualMemoryAccessType` | None | str
        Access flags for peers.
    """
    allocation_type: VirtualMemoryAllocationType = VirtualMemoryAllocationType.PINNED
    location_type: VirtualMemoryLocationType = VirtualMemoryLocationType.DEVICE
    handle_type: VirtualMemoryHandleType = VirtualMemoryHandleType.POSIX_FD
    granularity: VirtualMemoryGranularityType = VirtualMemoryGranularityType.RECOMMENDED
    gpu_direct_rdma: bool = False
    addr_hint: int | None = 0
    addr_align: int | None = None
    peers: Iterable[int] = field(default_factory=tuple)
    self_access: VirtualMemoryAccessType = VirtualMemoryAccessType.READ_WRITE
    peer_access: VirtualMemoryAccessType = VirtualMemoryAccessType.READ_WRITE
    _a = driver.CUmemAccess_flags
    _access_flags = {VirtualMemoryAccessType.READ_WRITE: _a.CU_MEM_ACCESS_FLAGS_PROT_READWRITE, VirtualMemoryAccessType.READ: _a.CU_MEM_ACCESS_FLAGS_PROT_READ, None: 0}
    _h = driver.CUmemAllocationHandleType
    _handle_types = {None: _h.CU_MEM_HANDLE_TYPE_NONE, VirtualMemoryHandleType.POSIX_FD: _h.CU_MEM_HANDLE_TYPE_POSIX_FILE_DESCRIPTOR, VirtualMemoryHandleType.WIN32_KMT: _h.CU_MEM_HANDLE_TYPE_WIN32_KMT, VirtualMemoryHandleType.FABRIC: _h.CU_MEM_HANDLE_TYPE_FABRIC}
    _g = driver.CUmemAllocationGranularity_flags
    _granularity = {VirtualMemoryGranularityType.RECOMMENDED: _g.CU_MEM_ALLOC_GRANULARITY_RECOMMENDED, VirtualMemoryGranularityType.MINIMUM: _g.CU_MEM_ALLOC_GRANULARITY_MINIMUM}
    _l = driver.CUmemLocationType
    _location_type = {VirtualMemoryLocationType.DEVICE: _l.CU_MEM_LOCATION_TYPE_DEVICE, VirtualMemoryLocationType.HOST: _l.CU_MEM_LOCATION_TYPE_HOST, VirtualMemoryLocationType.HOST_NUMA: _l.CU_MEM_LOCATION_TYPE_HOST_NUMA, VirtualMemoryLocationType.HOST_NUMA_CURRENT: _l.CU_MEM_LOCATION_TYPE_HOST_NUMA_CURRENT}
    _t = driver.CUmemAllocationType
    _allocation_type = {VirtualMemoryAllocationType.PINNED: _t.CU_MEM_ALLOCATION_TYPE_PINNED}

    @staticmethod
    def _access_to_flags(spec: VirtualMemoryAccessType | None) -> int: ...
    @staticmethod
    def _allocation_type_to_driver(spec: VirtualMemoryAllocationType) -> int: ...
    @staticmethod
    def _location_type_to_driver(spec: VirtualMemoryLocationType) -> int: ...
    @staticmethod
    def _handle_type_to_driver(spec: VirtualMemoryHandleType | None) -> int: ...
    @staticmethod
    def _granularity_to_driver(spec: VirtualMemoryGranularityType) -> int: ...

class VirtualMemoryBuffer(Buffer):
    """A :class:`Buffer` returned by :class:`VirtualMemoryResource`.

    The buffer owns its address reservations, physical allocations and
    mappings through its device pointer handle; closing it is the only way
    to release them. A buffer returned by
    :meth:`VirtualMemoryResource.modify_allocation` aliases the buffer it
    was grown from: the two share their physical memory, and that memory is
    freed when the last buffer that maps it closes.
    """
    def close(self, stream: Stream | GraphBuilder | None=None) -> None:
        """Release this buffer's share of its address range.

        The mappings, reservations and physical allocations go away when the
        last buffer that maps them closes. Before it unmaps, the resource
        synchronizes every deallocation stream the buffers of the range
        recorded. Virtual memory deallocation is synchronous and cannot be
        captured, so closing on a capturing stream raises and leaves the
        buffer open.

        Parameters
        ----------
        stream : :obj:`~_stream.Stream` | :obj:`~graph.GraphBuilder`, optional
            If given, replaces the recorded deallocation stream, as for
            :meth:`Buffer.close`.
        """

class VirtualMemoryResource(MemoryResource):
    """Create a device memory resource that uses the CUDA VMM APIs to allocate memory.

    Parameters
    ----------
    device_id : Device | int
        Device for which a memory resource is constructed.

    config : VirtualMemoryResourceOptions, optional
        A configuration object for the VirtualMemoryResource


    Warning
    -------
        This is a low-level API that is provided only for convenience. Make sure you fully understand
        how CUDA Virtual Memory Management works before using this. Other MemoryResource subclasses
        in cuda.core should already meet the common needs.

    Notes
    -----
    Every buffer this resource returns is a :class:`VirtualMemoryBuffer` that
    owns its address reservations, physical allocations and mappings; closing
    the buffer releases them. :meth:`deallocate` is not involved in that path.
    """
    device: object
    config: object

    def __init__(self, device_id: Device | int, config: VirtualMemoryResourceOptions | None=None) -> None: ...
    def allocate(self, size: int, *, stream: Stream | GraphBuilder | None=None) -> VirtualMemoryBuffer:
        """
        Allocate a buffer of the given size using CUDA virtual memory.

        Parameters
        ----------
        size : int
            The size in bytes of the buffer to allocate. It is rounded up to the
            allocation granularity; the returned buffer reports the rounded size.
        stream : :obj:`~_stream.Stream` | :obj:`~graph.GraphBuilder`, optional
            Keyword-only. The allocation itself is synchronous. A real stream is
            recorded as the buffer's deallocation stream and synchronized when
            the buffer closes; with `None` or a default-stream token the legacy
            default stream of the resource's device is recorded instead.

        Returns
        -------
        VirtualMemoryBuffer
            A buffer that owns its reservation, physical allocation and mapping.

        Raises
        ------
        CUDAError
            If any CUDA driver API call fails during allocation. Nothing is
            left allocated when this method raises.
        """
    def modify_allocation(self, buf: Buffer, new_size: int, config: VirtualMemoryResourceOptions | None=None) -> VirtualMemoryBuffer:
        """
        Grow a buffer of this resource to at least ``new_size`` bytes.

        The buffer passed in stays open and usable. The returned buffer aliases
        it: both map the same physical memory, which is freed when the last of
        the two closes. When the driver can extend the address range in place,
        the returned buffer has the same pointer; otherwise it has a new one and
        the existing contents are reachable through both.

        This method is not thread-safe with respect to two buffers that share an
        address range.

        Parameters
        ----------
        buf : VirtualMemoryBuffer
            A buffer returned by :meth:`allocate` or by this method.
        new_size : int
            The requested total size in bytes; rounded up to the granularity.
        config : VirtualMemoryResourceOptions, optional
            Configuration for the new physical memory chunk only. Existing
            chunks keep the access they were created with, and the resource's
            own configuration is unchanged.

        Returns
        -------
        VirtualMemoryBuffer
            ``buf`` itself when it already covers ``new_size``; otherwise a new
            buffer of the rounded size.

        Raises
        ------
        TypeError
            If ``buf`` did not come from this resource.
        CUDAError
            If a driver call fails. ``buf`` is untouched when this method raises.
        """
    def deallocate(self, ptr: DevicePointerType, size: int, *, stream: Stream | GraphBuilder | None=None) -> None:
        """
        Unmap and free one address range that was reserved and mapped outside this resource.

        Buffers returned by :meth:`allocate` and :meth:`modify_allocation` free
        themselves when they close and never call this method. It exists for
        raw pointers wrapped with :meth:`Buffer.from_handle` with ``mr`` set to
        this resource: the range must be exactly one reservation, and the caller
        must already have released its own ``cuMemCreate`` handle, so the
        physical memory is freed by the unmap.

        Parameters
        ----------
        ptr : DevicePointerType
            The start of the reservation.
        size : int
            The size of the reservation in bytes.
        stream : :obj:`~_stream.Stream` | :obj:`~graph.GraphBuilder`, optional
            Keyword-only. If given, ``stream.sync()`` is called before the
            range is unmapped, except for a default-stream token on a
            host-located resource, which has no context to synchronize in.
        """
    @property
    def is_device_accessible(self) -> bool:
        """
        Indicates whether the allocated memory is accessible from the device.
        """
    @property
    def is_host_accessible(self) -> bool:
        """
        Indicates whether the allocated memory is accessible from the host.
        """
    @property
    def is_ipc_enabled(self) -> bool:
        """Return False. Buffers of this resource cannot be shared through IPC descriptors."""
    @property
    def device_id(self) -> int:
        """
        Get the device ID associated with this memory resource.

        Returns:
            int: CUDA device ID. -1 if the memory resource allocates host memory
        """
    def __repr__(self) -> str:
        """
        Return a string representation of the VirtualMemoryResource.

        Returns:
            str: A string describing the object
        """
