# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import os
import subprocess
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
import check_precommit_installed as mod

WARNING_TEXT = "pre-commit git hook is not installed"


def _write_hook(hooks_dir, body=mod.MARKER):
    hooks_dir.mkdir(parents=True, exist_ok=True)
    (hooks_dir / "pre-commit").write_bytes(body)


@pytest.mark.agent_authored(model="claude-opus-5")
def test_installed_hook_is_quiet(tmp_path, monkeypatch, capsys):
    hooks = tmp_path / "hooks"
    _write_hook(hooks, b"#!/bin/sh\n# File generated by pre-commit\n")
    monkeypatch.setattr(mod, "_git_hooks_dir", lambda: str(hooks))

    assert mod.main() == 0
    assert WARNING_TEXT not in capsys.readouterr().err


@pytest.mark.agent_authored(model="claude-opus-5")
def test_missing_hook_warns_and_succeeds(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr(mod, "_git_hooks_dir", lambda: str(tmp_path / "hooks"))

    assert mod.main() == 0
    assert WARNING_TEXT in capsys.readouterr().err


@pytest.mark.agent_authored(model="claude-opus-5")
def test_foreign_hook_warns_and_succeeds(tmp_path, monkeypatch, capsys):
    """A hook installed by something other than pre-commit lacks the marker."""
    hooks = tmp_path / "hooks"
    _write_hook(hooks, b"#!/bin/sh\necho hand-written hook\n")
    monkeypatch.setattr(mod, "_git_hooks_dir", lambda: str(hooks))

    assert mod.main() == 0
    assert WARNING_TEXT in capsys.readouterr().err


@pytest.mark.agent_authored(model="claude-opus-5")
def test_outside_a_git_work_tree_warns_and_succeeds(tmp_path, monkeypatch, capsys):
    """`git rev-parse` exits 128 outside a work tree.

    check=True turned that into a CalledProcessError traceback and a non-zero
    exit, even though this check is advisory and main() returns 0 on both of
    its own branches.
    """
    monkeypatch.chdir(tmp_path)

    assert mod.main() == 0
    assert WARNING_TEXT in capsys.readouterr().err


@pytest.mark.agent_authored(model="claude-opus-5")
def test_git_missing_from_path_warns_and_succeeds(monkeypatch, capsys):
    def no_git(*args, **kwargs):
        raise FileNotFoundError(2, "No such file or directory: 'git'")

    monkeypatch.setattr(subprocess, "run", no_git)

    assert mod.main() == 0
    assert WARNING_TEXT in capsys.readouterr().err


@pytest.mark.agent_authored(model="claude-opus-5")
def test_unreadable_hook_path_warns_and_succeeds(tmp_path, monkeypatch, capsys):
    """The open() guard only caught FileNotFoundError, so anything else that
    makes the path unreadable escaped as a traceback."""
    hooks = tmp_path / "hooks"
    (hooks / "pre-commit").mkdir(parents=True)  # a directory, not a file
    monkeypatch.setattr(mod, "_git_hooks_dir", lambda: str(hooks))

    assert mod.main() == 0
    assert WARNING_TEXT in capsys.readouterr().err
