# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

"""Prepare the JUnit XML files from every CI configuration for Allure Report 3.

The test workflows upload one ``test-results-<configuration>`` artifact per
job, each holding one JUnit XML file per suite. Allure reads JUnit XML
directly, but it identifies a test by class name and test name only, so the
same test from several configurations would collapse into "retries" of one
result. This script gives every ``<testsuite>`` a ``package`` attribute that
names its configuration, which Allure turns into a ``package`` label, and
writes an ``allurerc.mjs`` whose ``environments`` map that label back to one
environment per configuration. The report then keeps the configurations
apart and shows a test's result in every configuration side by side.

Usage::

    python ci/tools/allure_prepare.py --results test-results \\
        --output allure-results --config allurerc.mjs
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ARTIFACT_PREFIX = "test-results-"
MODE_PREFIX = "standard-"


def configuration_name(artifact_dir: Path) -> str:
    """Return the configuration name encoded in an artifact directory name."""
    name = artifact_dir.name
    if name.startswith(ARTIFACT_PREFIX):
        name = name[len(ARTIFACT_PREFIX) :]
    if name.startswith(MODE_PREFIX):
        name = name[len(MODE_PREFIX) :]
    return name


def environment_id(name: str, taken: set[str]) -> str:
    """Return a unique Allure environment id: ``[A-Za-z0-9_-]``, at most 64 characters."""
    base = re.sub(r"[^A-Za-z0-9_-]", "-", name)[:60] or "configuration"
    candidate = base
    counter = 2
    while candidate in taken:
        candidate = f"{base}-{counter}"
        counter += 1
    taken.add(candidate)
    return candidate


def prepare(results: Path, output: Path) -> dict[str, int]:
    """Copy every JUnit file into ``output`` with its configuration as the suite package.

    Returns the number of files copied per configuration.
    """
    output.mkdir(parents=True, exist_ok=True)
    counts: dict[str, int] = {}
    for xml_path in sorted(results.rglob("*.xml")):
        configuration = configuration_name(xml_path.parent)
        # The files come from our own test jobs, not from an untrusted source.
        tree = ET.parse(xml_path)  # noqa: S314
        for suite in tree.iter("testsuite"):
            suite.set("package", configuration)
        tree.write(output / f"{configuration}-{xml_path.name}", encoding="utf-8", xml_declaration=True)
        counts[configuration] = counts.get(configuration, 0) + 1
    return counts


def render_config(report_name: str, configurations: list[str]) -> str:
    """Return the allurerc.mjs text with one environment per configuration."""
    taken: set[str] = set()
    entries = []
    for configuration in configurations:
        env_id = json.dumps(environment_id(configuration, taken))
        value = json.dumps(configuration)
        entries.append(
            f"    {env_id}: {{\n"
            f"      name: {value},\n"
            f'      matcher: ({{ labels }}) => labels.some(({{ name, value }}) => name === "package" && value === {value}),\n'
            f"    }},"
        )
    return (
        "// Generated by ci/tools/allure_prepare.py: one environment per CI configuration.\n"
        "export default {\n"
        f"  name: {json.dumps(report_name)},\n"
        "  environments: {\n" + "\n".join(entries) + "\n  },\n};\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Prepare CI JUnit XML files for Allure Report 3.")
    parser.add_argument(
        "--results", type=Path, required=True, help="directory with the downloaded test-results-* artifacts"
    )
    parser.add_argument(
        "--output", type=Path, required=True, help="flat directory of JUnit files for 'allure generate'"
    )
    parser.add_argument("--config", type=Path, required=True, help="path of the allurerc.mjs to write")
    parser.add_argument("--report-name", default="cuda-python test results", help="title of the report")
    args = parser.parse_args(argv)

    counts = prepare(args.results, args.output)
    if not counts:
        print(f"error: no JUnit XML files under {args.results}", file=sys.stderr)
        return 1
    args.config.write_text(render_config(args.report_name, sorted(counts)), encoding="utf-8")
    for configuration, count in sorted(counts.items()):
        print(f"{configuration}: {count} files")
    print(f"{len(counts)} configurations -> {args.output}; config written to {args.config}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
