# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/NVIDIA/cuda-python/discussions
    about: Check out our Discussions page to ask and answer questions.
