name: Release Checklist
description: Release managers need to go through this check list and ensure all tasks are done
body:
  - type: markdown
    attributes:
      value: |
        Please go through this checklist and ensure all tasks are completed.

  - type: checkboxes
    id: cuda-bindings-tasks
    attributes:
      label: Tasks for cuda-bindings / cuda-python release
      options:
        - label: "Push any internal updates for accommodating a new CTK release to the public (**IMPORTANT**: Need to wait for CTK posting!)"
        - label: Bump the version
        - label: Follow the check list for `cuda-core` below for the remaining steps

  - type: checkboxes
    id: cuda-core-tasks
    attributes:
      label: Tasks for cuda-core release
      options:
        - label: File an internal nvbug to communicate test plan & release schedule with QA
        - label: Ensure all pending PRs are reviewed, tested, and merged
        - label: Bump the version
        - label: Create a public rc tag
        - label: "Point QA to fetch public artifacts (wheels) from the GHA run ID, example: `gh run download 12323257563 -p \"cuda-core*\" -R NVIDIA/cuda-python`"
        - label: Wait for QA reports and fix any issues found
        - label: Finalize the doc update, including release notes
        - label: Update the docs for the new version
        - label: Create a public release tag
        - label: If any code change happens, rebuild the wheels from the new tag
        - label: Upload wheels to PyPI
        - label: Finalize the announcement update
        - label: Send out the announcement internally
        - label: Send out the announcement externally (GitHub Release -> Announcement)
        - label: Update the conda recipe & release conda packages
        - label: Post-release QA
