# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

import importlib.util
import zipfile
from pathlib import Path

import pytest

TOOLS = Path(__file__).resolve().parent.parent


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


tool = _load("cuda_core_bindings_floor", TOOLS / "cuda_core_bindings_floor.py")

FLOORS = {12: (12, 9, 8), 13: (13, 4, 1)}


def _build_info(major):
    floor = FLOORS[major]
    return (
        "# Generated by build_hooks.py at build time. Do not edit or commit.\n"
        f"CUDA_MAJOR = {major}\n"
        f"CUDA_VERSION = {major * 1000 + floor[1] * 10}  # the cuda.h this build compiled against\n"
        f"CUDA_BINDINGS_FLOOR = {floor!r}\n"
        f"CUDA_BINDINGS_BUILD_VERSION = '{major}.{floor[1]}.{floor[2]}'\n"
    )


def _wheel(tmp_path, entries):
    path = tmp_path / "cuda_core-1.3.0-cp312-cp312-linux_x86_64.whl"
    with zipfile.ZipFile(path, "w") as zf:
        for name, major in entries.items():
            zf.writestr(name, _build_info(major))
    return path


@pytest.mark.agent_authored(model="claude-fable-5-1")
@pytest.mark.parametrize("major", [12, 13])
def test_reads_the_merged_wheel_layout(tmp_path, major):
    wheel = _wheel(tmp_path, {"cuda/core/cu12/_build_info.py": 12, "cuda/core/cu13/_build_info.py": 13})
    assert tool.floor_from_wheel(wheel, major) == ".".join(map(str, FLOORS[major]))


@pytest.mark.agent_authored(model="claude-fable-5-1")
def test_reads_a_single_major_wheel(tmp_path):
    wheel = _wheel(tmp_path, {"cuda/core/_build_info.py": 13})
    assert tool.floor_from_wheel(wheel, 13) == "13.4.1"


@pytest.mark.agent_authored(model="claude-fable-5-1")
def test_rejects_a_single_major_wheel_of_another_major(tmp_path):
    wheel = _wheel(tmp_path, {"cuda/core/_build_info.py": 13})
    with pytest.raises(SystemExit, match="records a CUDA 13 build, not CUDA 12"):
        tool.floor_from_wheel(wheel, 12)


@pytest.mark.agent_authored(model="claude-fable-5-1")
def test_rejects_a_wheel_without_the_build_record(tmp_path):
    wheel = _wheel(tmp_path, {})
    with pytest.raises(SystemExit, match="contains no build for CUDA 13"):
        tool.floor_from_wheel(wheel, 13)


@pytest.mark.agent_authored(model="claude-fable-5-1")
def test_rejects_a_build_record_without_the_floor():
    with pytest.raises(SystemExit, match="does not assign CUDA_BINDINGS_FLOOR"):
        tool.floor_from_source("CUDA_MAJOR = 13\n", 13)


@pytest.mark.agent_authored(model="claude-fable-5-1")
def test_cli_prints_the_floor(tmp_path, capsys):
    wheel = _wheel(tmp_path, {"cuda/core/_build_info.py": 13})
    assert tool.main(["--wheel", str(wheel), "--major", "13"]) == 0
    assert capsys.readouterr().out.strip() == "13.4.1"
