# This file was generated by stubgen-pyx v0.2.6 from cuda_core/cuda/core/_utils/_wsl_locale.pyx

from __future__ import annotations


class c_locale_guard:
    """Context manager that pins the calling thread to the "C" locale.

    Uses POSIX newlocale/uselocale/freelocale so other threads' view of the
    locale is unaffected. Restores the previous thread locale on exit.
    """

    def __cinit__(self) -> None:
        ...

    def __enter__(self):
        ...

    def __exit__(self, exc_type, exc_val, exc_tb):
        ...