# This file was generated by stubgen-pyx v0.2.22 from cuda_core/cuda/core/_utils/cuda_utils.pyx

from typing import Any, Callable, NamedTuple

from cuda.bindings import cydriver
from cuda.bindings import driver as driver
from cuda.bindings import nvrtc as nvrtc
from cuda.bindings import runtime as runtime

_keep_driver_in_stub: driver.CUresult
_keep_nvrtc_in_stub: nvrtc.nvrtcResult
_keep_runtime_in_stub: runtime.cudaError_t
_fork_warning_checked = False

class CUDAError(Exception):
    """Raised when a CUDA driver or runtime call fails.

    The message names the CUDA error and, when one is known, explains it. A
    secondary failure observed while the error was being raised, such as a
    failed restoration of the caller's CUDA context, is attached as a note
    (``__notes__``) on Python 3.11 and newer and appended to the message on
    older interpreters. See the error handling page of the ``cuda.core``
    documentation for the guarantees an exception provides.
    """

class CUDAWarning(RuntimeWarning):
    """Warning issued when ``cuda.core`` hits a CUDA error it cannot raise.

    ``cuda.core`` raises exceptions for failures in ordinary calls. Some failures
    happen where no exception can propagate: while a resource is released by the
    garbage collector or by a CUDA callback, including the driver calls that
    switch and restore the CUDA context around such a release. Those failures
    are reported as this warning instead, and the affected resource may have
    leaked.

    Filter on this category to make such failures fatal in tests::

        warnings.filterwarnings("error", category=cuda.core.CUDAWarning)

    Because the report comes from a destructor, an escalated warning cannot be
    raised into user code; it is delivered through :func:`sys.unraisablehook`
    (which pytest surfaces as ``PytestUnraisableExceptionWarning``).

    .. versionadded:: 1.3.0
    """

class NVRTCError(CUDAError):
    """Raised when an NVRTC call fails; the compiler log is appended when available."""

class ComputeCapability(NamedTuple):
    """A named tuple of (major, minor) CUDA compute capability version numbers."""
    major: int
    minor: int

class Transaction:
    """
    A context manager for transactional operations with failure and exit callbacks.

    Failure callbacks are executed in LIFO order if the transaction exits without being committed.
    Exit callbacks always run: in LIFO order on rollback or FIFO order during commit.

    Usage:
        with Transaction() as txn:
            txn.on_failure(some_cleanup_function, arg1, arg2)
            txn.on_exit(some_finalize_function, arg1, arg2)
            # ... perform operations ...
            txn.commit()

    Methods:
        on_failure(fn, *args, **kwargs): Register a callback to be called on rollback.
        on_exit(fn, *args, **kwargs): Register a callback to be called on rollback or commit.
        commit(): Disarm failure callbacks and run exit callbacks.
    """
    def __init__(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc, tb): ...
    def _register(self, callback: Callable[[], Any], on_commit: bool) -> None: ...
    def on_failure(self, fn: Callable[..., Any], /, *args: Any, **kwargs) -> None:
        """Register a failure callback (runs if the with-block exits without commit())."""
    def on_exit(self, fn: Callable[..., Any], /, *args: Any, **kwargs) -> None:
        """Register an exit callback (runs exactly once, on rollback or during commit())."""
    def commit(self) -> None:
        """
        Disarm all failure callbacks, then run exit callbacks in FIFO order.
        """

def cast_to_3_tuple(label: str, cfg: int | tuple[int, ...]) -> tuple[int, int, int]: ...
def _check_driver_error(error: cydriver.CUresult) -> int: ...
def _check_runtime_error(error) -> int: ...
def _check_nvrtc_error(error, handle=None) -> int: ...
def handle_return(result: tuple[Any, ...], handle: object | None=None) -> Any: ...
def check_or_create_options(cls: type, options: object, options_description: str='', keep_none: bool=False) -> object:
    """
    Create the specified options dataclass from a dictionary of options or None.
    """
def _handle_boolean_option(option: bool) -> str:
    """
    Convert a boolean option to a string representation.
    """
def precondition(checker: Callable[..., None], what: str='') -> Callable[..., Any]:
    """
    A decorator that adds checks to ensure any preconditions are met.

    Args:
        checker: The function to call to check whether the preconditions are met. It has
        the same signature as the wrapped function with the addition of the keyword argument `what`.
        what: A string that is passed in to `checker` to provide context information.

    Returns:
        Callable: A decorator that creates the wrapping.
    """
def is_sequence(obj: object) -> bool:
    """
    Check if the given object is a sequence (list or tuple).
    """
def is_nested_sequence(obj: object) -> bool:
    """
    Check if the given object is a nested sequence (list or tuple with atleast one list or tuple element).
    """
def reset_fork_warning() -> None:
    """Reset the fork warning check flag for testing purposes.

    This function is intended for use in tests to allow multiple test runs
    to check the warning behavior.
    """
def _parse_fill_value(value) -> tuple[Any, ...]:
    """Parse a fill/memset value into (raw_value, element_size).

    Parameters
    ----------
    value : int or buffer-protocol object
        - int: Must be in range [0, 256). Treated as 1-byte fill.
        - bytes or buffer-protocol: Must be 1, 2, or 4 bytes.

    Returns
    -------
    tuple of (int, int)
        (raw_value, element_size) where element_size is 1, 2, or 4.

    Raises
    ------
    OverflowError
        If int value is outside [0, 256).
    TypeError
        If value is not an int and does not support the buffer protocol.
    ValueError
        If value byte length is not 1, 2, or 4.
    """
def check_multiprocessing_start_method() -> None:
    """Check if multiprocessing start method is 'fork' and warn if so."""
