# This file was generated by stubgen-pyx v0.2.6 from cuda_core/cuda/core/_utils/version.pyx

from __future__ import annotations

import functools


@functools.cache
def binding_version() -> tuple[int, int, int]:
    """Return the cuda-bindings version as a (major, minor, patch) triple."""

@functools.cache
def driver_version() -> tuple[int, int, int]:
    """Return the CUDA driver version as a (major, minor, patch) triple."""