#!/usr/bin/env bash

build_ci() {
    set -xeou pipefail

    cd "${REPO_DIR}"

    export CUDA_HOME="${CONDA_PREFIX}/targets/x86_64-linux"
    export PARALLEL_LEVEL=$(nproc --ignore 1)

    python setup.py bdist_wheel
}

build_ci_fake() {
    set -xeou pipefail

    cd "${REPO_DIR}"

    mkdir "${REPO_DIR}"/dist

    cp cuda_python-12.6.0+28.g3453074-cp311-cp311-linux_x86_64.whl "${REPO_DIR}"/dist

}

build_project() {
    set -xeou pipefail

    export PYTHONUNBUFFERED=1

    . setup-utils;
    init_build_env "$@";

    git config --global --add safe.directory "$REPO_DIR/.git"

    case "${BUILD_TYPE}" in
        # TODO: uncomment and delete line below it
        # ci) build_ci;;
        ci) build_ci_fake ;;
        *) return 1;;
    esac
}

(build_project "$@");
