#!/usr/bin/env bash

build_ci() {
    set -xeou pipefail

    export CUDA_HOME="${CONDA_PREFIX}/targets/x86_64-linux"
    export PARALLEL_LEVEL=$(nproc --ignore 1)

    cd "${REPO_DIR}/cuda_bindings"
    python setup.py bdist_wheel
    
    cd "${REPO_DIR}/cuda_core"
    python setup.py bdist_wheel
}

build_project() {
    set -xeou pipefail

    export PYTHONUNBUFFERED=1

    . setup-utils;
    init_build_env "$@";

    git config --global --add safe.directory "$REPO_DIR/.git"

    case "${BUILD_TYPE}" in
        ci) build_ci;;
        *) return 1;;
    esac
}

(build_project "$@");
