#!/usr/bin/env bash

activate_conda_env() {
    set +xu
    eval "$(conda shell.bash hook)"
    conda activate "${CONDA_ENV}";
    set -xu
    : ${PYTHON_VERSION:=$(python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")}
    export PYTHON_VERSION
}

conda_info() {
    set +x
    conda info
    set -x
}
