#!/usr/bin/env bash

set_initial_env() {
    set -xeuo pipefail

    export PATH="${PATH}:${REPO_DIR}/continuous_integration/scripts"
}

entrypoint() {
    set -xeuo pipefail
    set_initial_env;

    git config --global --add safe.directory "$REPO_DIR/.git"

    cd "${REPO_DIR}"

    exec "$@";
}

entrypoint "$@";
