#!/usr/bin/env bash

set -x

make_ci_env() {
    mamba env create -n "${CONDA_ENV}" -f "${REPO_DIR}/continuous_integration/environment.yml"
}

make_conda_env() {
    set -xeuo pipefail

    . setup-utils;
    set_base_defs;

    case "$1" in
        ci) make_ci_env;;
        test) make_test_env;;
        *) return 1;;
    esac

    return 0;
}

(make_conda_env "$@");
