# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

$schema: https://moonrepo.dev/schemas/v2/tasks.json

inheritedBy:
  tag: installed-test-package

tasks:
  test-installed-linux:
    command: bash
    args: [ci/tools/run-tests, '$project']
    inputs:
      - '@group(package)'
      - '/ci/tools/run-tests'
      - '/ci/test-matrix.yml'
      - '/ci/tools/env-vars'
      - '/tests/**/*'
      - '/.github/workflows/build-wheel.yml'
      - '/ci/tools/guess_latest.sh'
      - '/ci/tools/install_gpu_driver.sh'
      - '/.github/workflows/test-wheel-linux.yml'
    tags: [ci-test-linux]
    type: test
    options:
      mutex: ci-python-gpu
      os: linux
      runInCI: true

  test-installed-windows:
    command: bash
    args: [ci/tools/run-tests, '$project']
    inputs:
      - '@group(package)'
      - '/ci/tools/run-tests'
      - '/ci/test-matrix.yml'
      - '/ci/tools/env-vars'
      - '/tests/**/*'
      - '/.github/workflows/build-wheel.yml'
      - '/ci/tools/configure_driver_mode.ps1'
      - '/ci/tools/install_gpu_driver.ps1'
      - '/.github/workflows/test-wheel-windows.yml'
    tags: [ci-test-windows]
    type: test
    options:
      mutex: ci-python-gpu
      os: windows
      runInCI: true
