# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Warn (without failing) if the pre-commit git hook is not installed.

This repo relies on pre-commit running on *every* commit: the SPDX header
updater and the .pyi stub generator only keep the tree consistent if they
run automatically via the installed git hook. Contributors who only run
`pre-commit run --all-files` manually (or never run pre-commit at all) can
end up with stale headers or stubs. This check can't block the commit
(if pre-commit isn't installed as a git hook, this script never runs
during `git commit` in the first place) but it does fire during manual
`pre-commit run` invocations and in CI, where it gives contributors a
visible nudge to run `pre-commit install`.
"""

import subprocess
import sys

MARKER = b"File generated by pre-commit"


def _git_hooks_dir() -> str | None:
    """Resolve the git hooks directory, or None if git cannot tell us.

    Anything that stops git from answering -- not inside a work tree, git
    missing from PATH, a broken repository -- leaves us unable to confirm the
    hook is installed, which is the same outcome as "not installed". This
    check is advisory (see the module docstring), so it must never turn a
    `pre-commit run` into a failure.
    """
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--git-path", "hooks"],  # noqa: S607
            capture_output=True,
            check=True,
            text=True,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    return result.stdout.strip() or None


def main() -> int:
    hooks_dir = _git_hooks_dir()

    installed = False
    if hooks_dir is not None:
        try:
            with open(f"{hooks_dir}/pre-commit", "rb") as f:
                installed = MARKER in f.read()
        except OSError:
            # Unreadable, a directory, a dangling symlink: all mean we cannot
            # confirm an installed hook, and none of them justify failing.
            installed = False

    if not installed:
        print(
            "\n"
            "==================== pre-commit WARNING ====================\n"
            "The pre-commit git hook is not installed in this checkout.\n"
            "Without it, checks only run when you invoke pre-commit\n"
            "manually, and will NOT run automatically on `git commit`.\n"
            "\n"
            "Fix this by running:\n"
            "\n"
            "    pre-commit install\n"
            "==============================================================\n",
            file=sys.stderr,
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
