# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Run stubgen-pyx for cuda_core and normalize the generated stub headers.

stubgen-pyx emits a path using the OS path separator in the first-line comment
(e.g. "# This file was generated by stubgen-pyx from cuda_core\\cuda\\...").
This wrapper rewrites that separator to "/" so committed stubs are identical
across platforms. Line-ending normalization is handled by .gitattributes.

This also forces stubgen-pyx to write files with UTF-8 encoding, which is not
the default on Windows.

This wrapper can be removed once these stubgen-pyx issues are resolved:
    https://github.com/jon-edward/stubgen-pyx/issues/41
    https://github.com/jon-edward/stubgen-pyx/issues/42
"""

from __future__ import annotations

import os
import pathlib
import re
import subprocess
import sys

_HEADER_PREFIX = b"# This file was generated by stubgen-pyx"
# Marker for per-parameter stub-public annotation overrides; see _collect_stub_overrides.
_STUB_DIRECTIVE = "# stub:"


def _normalize_stub_headers(root: pathlib.Path) -> None:
    for stub in root.rglob("*.pyi"):
        data = stub.read_bytes()
        newline = data.find(b"\n")
        first_line = data[:newline] if newline != -1 else data
        if not first_line.startswith(_HEADER_PREFIX) or b"\\" not in first_line:
            continue
        stub.write_bytes(first_line.replace(b"\\", b"/") + data[newline:])


def _collect_stub_overrides(root: pathlib.Path) -> dict[pathlib.Path, list[tuple[str, str]]]:
    """Collect # stub: annotation overrides declared in .pyx source files.

    A line in a .pyx file of the form
        param: OrigType = default  # stub: NewType
    causes the postprocessor to replace "param: OrigType" with "param: NewType"
    in the corresponding generated .pyi, so the public stub can differ from the
    runtime annotation without editing generated files by hand.
    """
    overrides: dict[pathlib.Path, list[tuple[str, str]]] = {}
    for pyx in sorted(root.rglob("*.pyx")):
        pyi = pyx.with_suffix(".pyi")
        pairs = []
        for line in pyx.read_text(encoding="utf-8").splitlines():
            if _STUB_DIRECTIVE not in line:
                continue
            code_part, _, directive = line.partition(_STUB_DIRECTIVE)
            # Directive format: "param_name: NewType"
            m_dir = re.match(r"^(\w+)\s*:\s*(.+)$", directive.strip())
            if not m_dir:
                continue
            param_name, new_type = m_dir.group(1), m_dir.group(2).strip()
            # Locate "param_name: " in the source line and extract the type.
            # str.find + partition avoids regex bracket-balance issues (e.g. dict[str, object]).
            marker = f"{param_name}: "
            idx = code_part.find(marker)
            if idx == -1:
                continue
            after_param = code_part[idx + len(marker) :]
            original_type = after_param.partition(" = ")[0].strip()
            pairs.append((f"{param_name}: {original_type}", f"{param_name}: {new_type}"))
        if pairs:
            overrides[pyi] = pairs
    return overrides


def _apply_stub_overrides(overrides: dict[pathlib.Path, list[tuple[str, str]]]) -> None:
    """Apply annotation overrides to generated .pyi files."""
    for pyi, pairs in overrides.items():
        if not pyi.exists():
            continue
        content = pyi.read_text(encoding="utf-8")
        for original, replacement in pairs:
            content = content.replace(original, replacement)
        pyi.write_text(content, encoding="utf-8")


def main() -> int:
    env = os.environ.copy()
    env.setdefault("PYTHONUTF8", "1")
    env.setdefault("PYTHONIOENCODING", "utf-8")
    # Collect overrides before running stubgen so we read clean source.
    overrides = _collect_stub_overrides(pathlib.Path("cuda_core/cuda"))
    result = subprocess.run(
        ["stubgen-pyx", "cuda_core/cuda", "--continue-on-error", "--include-private"],  # noqa: S607
        env=env,
    )
    if result.returncode != 0:
        return result.returncode
    _normalize_stub_headers(pathlib.Path("cuda_core/cuda"))
    _apply_stub_overrides(overrides)
    return 0


if __name__ == "__main__":
    sys.exit(main())
