# SPDX-FileCopyrightText: Copyright (c) 2024-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Get the PR number

description: Get the PR number without relying on the pull_request* event triggers.

runs:
  using: composite
  steps:
    - name: Get PR info
      uses: nv-gha-runners/get-pr-info@main
      id: get-pr-info

    - name: Extract PR number
      shell: bash --noprofile --norc -xeuo pipefail {0}
      run: |
        trap 'echo "Error at line $LINENO"; exit 1' ERR
        PR_NUMBER="${{ fromJSON(steps.get-pr-info.outputs.pr-info).number }}"
        if [[ -z "$PR_NUMBER" ]]; then
          echo "Cannot extract PR number for ref: ${{ github.ref_name }}"
          exit 1
        fi
        echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        echo "BUILD_PREVIEW=1" >> $GITHUB_ENV
