# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: "CI: Backport the merged PR"

on:
  pull_request_target:
    types: [closed, labeled]
    branches:
      - main

permissions:
  contents: write       # so it can comment
  pull-requests: write  # so it can create pull requests

jobs:
  backport:
    name: Backport pull request
    if: ${{ github.repository_owner == 'nvidia' &&
            github.event.pull_request.merged == true &&
            contains( github.event.pull_request.labels.*.name, 'to-be-backported')
         }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Load branch name
        id: get-branch
        run: |
          OLD_BRANCH=$(cat .github/BACKPORT_BRANCH)
          echo "OLD_BRANCH=${OLD_BRANCH}" >> $GITHUB_ENV

      - name: Create backport pull requests
        uses: korthout/backport-action@01619ebc9a6e3f6820274221b9956b3e7365000a  # v4.1.0
        with:
          copy_assignees: true
          copy_labels_pattern: true
          copy_requested_reviewers: true
          target_branches: ${{ env.OLD_BRANCH }}
