# SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: "CI: Summary"

on:
  workflow_call:

jobs:
  checks:
    name: Check job status
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checks
        uses: poseidon/wait-for-status-checks@899c768d191b56eef585c18f8558da19e1f3e707  # v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          match_pattern: "CI*"
          ignore_pattern: ".*Check job status.*"  # ignore self
