# Copyright (c) 2024-2025, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
#
# SPDX-License-Identifier: Apache-2.0

name: Add Triage Label

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add or check for existing labels
        # add the triage label only if no label has been added
        if: ${{ github.event.issue.labels[0] == null }}
        run: gh issue edit "$NUMBER" --add-label "triage"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
